name: Trivy IaC Scan (CloudFormation)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  trivy-iac-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy IaC scan (SARIF)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: "config"
          scan-ref: "."
          severity: "CRITICAL,HIGH,MEDIUM"
          format: "sarif"
          output: "trivy-iac-results.sarif"
          exit-code: "1"

      - name: Upload SARIF report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-iac-sarif-report
          path: trivy-iac-results.sarif
